# Generated by Django 5.0.7 on 2024-08-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_system', '0007_rename_first_name_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='product_class',
            new_name='product_category',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='e_invoice_carrier',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_barcode',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_system.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_system.product')),
            ],
        ),
    ]
